language: node_js

node_js:
  - "6"
  - "8"
  - "10"

# Use container-based Travis infrastructure.
sudo: false

cache: true

branches:
  only:
    - master

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn test --log-level=info
  - NODE_ENV=production node_modules/.bin/builder run build-static --log-level=info
