language: node_js

node_js:
  - "4"
  - "6"
  - "8"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn --version
  - yarn test
  - NODE_ENV=production node_modules/.bin/builder run build-static
